// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChannelSubscribersGetResponse.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ChannelSubscribersGetResponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ChannelSubscribersGetResponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "User.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ChannelSubscribersGetResponse_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ChannelSubscribersGetResponse_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ChannelSubscribersGetResponse_2eproto;
namespace AcFunDanmu {
namespace Im {
namespace Cloud {
namespace Channel {
class ChannelSubscribersGetResponse;
struct ChannelSubscribersGetResponseDefaultTypeInternal;
extern ChannelSubscribersGetResponseDefaultTypeInternal _ChannelSubscribersGetResponse_default_instance_;
}  // namespace Channel
}  // namespace Cloud
}  // namespace Im
}  // namespace AcFunDanmu
PROTOBUF_NAMESPACE_OPEN
template<> ::AcFunDanmu::Im::Cloud::Channel::ChannelSubscribersGetResponse* Arena::CreateMaybeMessage<::AcFunDanmu::Im::Cloud::Channel::ChannelSubscribersGetResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace AcFunDanmu {
namespace Im {
namespace Cloud {
namespace Channel {

// ===================================================================

class ChannelSubscribersGetResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:AcFunDanmu.Im.Cloud.Channel.ChannelSubscribersGetResponse) */ {
 public:
  inline ChannelSubscribersGetResponse() : ChannelSubscribersGetResponse(nullptr) {}
  ~ChannelSubscribersGetResponse() override;
  explicit PROTOBUF_CONSTEXPR ChannelSubscribersGetResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChannelSubscribersGetResponse(const ChannelSubscribersGetResponse& from);
  ChannelSubscribersGetResponse(ChannelSubscribersGetResponse&& from) noexcept
    : ChannelSubscribersGetResponse() {
    *this = ::std::move(from);
  }

  inline ChannelSubscribersGetResponse& operator=(const ChannelSubscribersGetResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChannelSubscribersGetResponse& operator=(ChannelSubscribersGetResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChannelSubscribersGetResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChannelSubscribersGetResponse* internal_default_instance() {
    return reinterpret_cast<const ChannelSubscribersGetResponse*>(
               &_ChannelSubscribersGetResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ChannelSubscribersGetResponse& a, ChannelSubscribersGetResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ChannelSubscribersGetResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChannelSubscribersGetResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChannelSubscribersGetResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChannelSubscribersGetResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChannelSubscribersGetResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChannelSubscribersGetResponse& from) {
    ChannelSubscribersGetResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChannelSubscribersGetResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "AcFunDanmu.Im.Cloud.Channel.ChannelSubscribersGetResponse";
  }
  protected:
  explicit ChannelSubscribersGetResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSubscriberFieldNumber = 1,
  };
  // repeated .AcFunDanmu.Im.Basic.User subscriber = 1;
  int subscriber_size() const;
  private:
  int _internal_subscriber_size() const;
  public:
  void clear_subscriber();
  ::AcFunDanmu::Im::Basic::User* mutable_subscriber(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Basic::User >*
      mutable_subscriber();
  private:
  const ::AcFunDanmu::Im::Basic::User& _internal_subscriber(int index) const;
  ::AcFunDanmu::Im::Basic::User* _internal_add_subscriber();
  public:
  const ::AcFunDanmu::Im::Basic::User& subscriber(int index) const;
  ::AcFunDanmu::Im::Basic::User* add_subscriber();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Basic::User >&
      subscriber() const;

  // @@protoc_insertion_point(class_scope:AcFunDanmu.Im.Cloud.Channel.ChannelSubscribersGetResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Basic::User > subscriber_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ChannelSubscribersGetResponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ChannelSubscribersGetResponse

// repeated .AcFunDanmu.Im.Basic.User subscriber = 1;
inline int ChannelSubscribersGetResponse::_internal_subscriber_size() const {
  return _impl_.subscriber_.size();
}
inline int ChannelSubscribersGetResponse::subscriber_size() const {
  return _internal_subscriber_size();
}
inline ::AcFunDanmu::Im::Basic::User* ChannelSubscribersGetResponse::mutable_subscriber(int index) {
  // @@protoc_insertion_point(field_mutable:AcFunDanmu.Im.Cloud.Channel.ChannelSubscribersGetResponse.subscriber)
  return _impl_.subscriber_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Basic::User >*
ChannelSubscribersGetResponse::mutable_subscriber() {
  // @@protoc_insertion_point(field_mutable_list:AcFunDanmu.Im.Cloud.Channel.ChannelSubscribersGetResponse.subscriber)
  return &_impl_.subscriber_;
}
inline const ::AcFunDanmu::Im::Basic::User& ChannelSubscribersGetResponse::_internal_subscriber(int index) const {
  return _impl_.subscriber_.Get(index);
}
inline const ::AcFunDanmu::Im::Basic::User& ChannelSubscribersGetResponse::subscriber(int index) const {
  // @@protoc_insertion_point(field_get:AcFunDanmu.Im.Cloud.Channel.ChannelSubscribersGetResponse.subscriber)
  return _internal_subscriber(index);
}
inline ::AcFunDanmu::Im::Basic::User* ChannelSubscribersGetResponse::_internal_add_subscriber() {
  return _impl_.subscriber_.Add();
}
inline ::AcFunDanmu::Im::Basic::User* ChannelSubscribersGetResponse::add_subscriber() {
  ::AcFunDanmu::Im::Basic::User* _add = _internal_add_subscriber();
  // @@protoc_insertion_point(field_add:AcFunDanmu.Im.Cloud.Channel.ChannelSubscribersGetResponse.subscriber)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Basic::User >&
ChannelSubscribersGetResponse::subscriber() const {
  // @@protoc_insertion_point(field_list:AcFunDanmu.Im.Cloud.Channel.ChannelSubscribersGetResponse.subscriber)
  return _impl_.subscriber_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Channel
}  // namespace Cloud
}  // namespace Im
}  // namespace AcFunDanmu

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ChannelSubscribersGetResponse_2eproto
