// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SessionFolderSyncResponse.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_SessionFolderSyncResponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_SessionFolderSyncResponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "SessionFolderBasic.pb.h"
#include "SessionReferenceUpdateItem.pb.h"
#include "SyncCookie.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_SessionFolderSyncResponse_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_SessionFolderSyncResponse_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_SessionFolderSyncResponse_2eproto;
namespace AcFunDanmu {
namespace Im {
namespace Cloud {
namespace SessionFolder {
class SessionFolderSyncResponse;
struct SessionFolderSyncResponseDefaultTypeInternal;
extern SessionFolderSyncResponseDefaultTypeInternal _SessionFolderSyncResponse_default_instance_;
}  // namespace SessionFolder
}  // namespace Cloud
}  // namespace Im
}  // namespace AcFunDanmu
PROTOBUF_NAMESPACE_OPEN
template<> ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderSyncResponse* Arena::CreateMaybeMessage<::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderSyncResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace AcFunDanmu {
namespace Im {
namespace Cloud {
namespace SessionFolder {

// ===================================================================

class SessionFolderSyncResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse) */ {
 public:
  inline SessionFolderSyncResponse() : SessionFolderSyncResponse(nullptr) {}
  ~SessionFolderSyncResponse() override;
  explicit PROTOBUF_CONSTEXPR SessionFolderSyncResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SessionFolderSyncResponse(const SessionFolderSyncResponse& from);
  SessionFolderSyncResponse(SessionFolderSyncResponse&& from) noexcept
    : SessionFolderSyncResponse() {
    *this = ::std::move(from);
  }

  inline SessionFolderSyncResponse& operator=(const SessionFolderSyncResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SessionFolderSyncResponse& operator=(SessionFolderSyncResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SessionFolderSyncResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SessionFolderSyncResponse* internal_default_instance() {
    return reinterpret_cast<const SessionFolderSyncResponse*>(
               &_SessionFolderSyncResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SessionFolderSyncResponse& a, SessionFolderSyncResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SessionFolderSyncResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SessionFolderSyncResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SessionFolderSyncResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SessionFolderSyncResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SessionFolderSyncResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SessionFolderSyncResponse& from) {
    SessionFolderSyncResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SessionFolderSyncResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse";
  }
  protected:
  explicit SessionFolderSyncResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionFolderBasicFieldNumber = 2,
    kAddedFieldNumber = 3,
    kRemovedFieldNumber = 4,
    kSyncCookieFieldNumber = 1,
    kNotFullFetchFieldNumber = 5,
    kClearLocalDataFieldNumber = 6,
  };
  // repeated .AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderBasic sessionFolderBasic = 2;
  int sessionfolderbasic_size() const;
  private:
  int _internal_sessionfolderbasic_size() const;
  public:
  void clear_sessionfolderbasic();
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderBasic* mutable_sessionfolderbasic(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderBasic >*
      mutable_sessionfolderbasic();
  private:
  const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderBasic& _internal_sessionfolderbasic(int index) const;
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderBasic* _internal_add_sessionfolderbasic();
  public:
  const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderBasic& sessionfolderbasic(int index) const;
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderBasic* add_sessionfolderbasic();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderBasic >&
      sessionfolderbasic() const;

  // repeated .AcFunDanmu.Im.Cloud.SessionFolder.SessionReferenceUpdateItem added = 3;
  int added_size() const;
  private:
  int _internal_added_size() const;
  public:
  void clear_added();
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem* mutable_added(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem >*
      mutable_added();
  private:
  const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem& _internal_added(int index) const;
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem* _internal_add_added();
  public:
  const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem& added(int index) const;
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem* add_added();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem >&
      added() const;

  // repeated .AcFunDanmu.Im.Cloud.SessionFolder.SessionReferenceUpdateItem removed = 4;
  int removed_size() const;
  private:
  int _internal_removed_size() const;
  public:
  void clear_removed();
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem* mutable_removed(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem >*
      mutable_removed();
  private:
  const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem& _internal_removed(int index) const;
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem* _internal_add_removed();
  public:
  const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem& removed(int index) const;
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem* add_removed();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem >&
      removed() const;

  // .AcFunDanmu.Im.Basic.SyncCookie syncCookie = 1;
  bool has_synccookie() const;
  private:
  bool _internal_has_synccookie() const;
  public:
  void clear_synccookie();
  const ::AcFunDanmu::Im::Basic::SyncCookie& synccookie() const;
  PROTOBUF_NODISCARD ::AcFunDanmu::Im::Basic::SyncCookie* release_synccookie();
  ::AcFunDanmu::Im::Basic::SyncCookie* mutable_synccookie();
  void set_allocated_synccookie(::AcFunDanmu::Im::Basic::SyncCookie* synccookie);
  private:
  const ::AcFunDanmu::Im::Basic::SyncCookie& _internal_synccookie() const;
  ::AcFunDanmu::Im::Basic::SyncCookie* _internal_mutable_synccookie();
  public:
  void unsafe_arena_set_allocated_synccookie(
      ::AcFunDanmu::Im::Basic::SyncCookie* synccookie);
  ::AcFunDanmu::Im::Basic::SyncCookie* unsafe_arena_release_synccookie();

  // bool notFullFetch = 5;
  void clear_notfullfetch();
  bool notfullfetch() const;
  void set_notfullfetch(bool value);
  private:
  bool _internal_notfullfetch() const;
  void _internal_set_notfullfetch(bool value);
  public:

  // bool clearLocalData = 6;
  void clear_clearlocaldata();
  bool clearlocaldata() const;
  void set_clearlocaldata(bool value);
  private:
  bool _internal_clearlocaldata() const;
  void _internal_set_clearlocaldata(bool value);
  public:

  // @@protoc_insertion_point(class_scope:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderBasic > sessionfolderbasic_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem > added_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem > removed_;
    ::AcFunDanmu::Im::Basic::SyncCookie* synccookie_;
    bool notfullfetch_;
    bool clearlocaldata_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SessionFolderSyncResponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SessionFolderSyncResponse

// .AcFunDanmu.Im.Basic.SyncCookie syncCookie = 1;
inline bool SessionFolderSyncResponse::_internal_has_synccookie() const {
  return this != internal_default_instance() && _impl_.synccookie_ != nullptr;
}
inline bool SessionFolderSyncResponse::has_synccookie() const {
  return _internal_has_synccookie();
}
inline const ::AcFunDanmu::Im::Basic::SyncCookie& SessionFolderSyncResponse::_internal_synccookie() const {
  const ::AcFunDanmu::Im::Basic::SyncCookie* p = _impl_.synccookie_;
  return p != nullptr ? *p : reinterpret_cast<const ::AcFunDanmu::Im::Basic::SyncCookie&>(
      ::AcFunDanmu::Im::Basic::_SyncCookie_default_instance_);
}
inline const ::AcFunDanmu::Im::Basic::SyncCookie& SessionFolderSyncResponse::synccookie() const {
  // @@protoc_insertion_point(field_get:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.syncCookie)
  return _internal_synccookie();
}
inline void SessionFolderSyncResponse::unsafe_arena_set_allocated_synccookie(
    ::AcFunDanmu::Im::Basic::SyncCookie* synccookie) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.synccookie_);
  }
  _impl_.synccookie_ = synccookie;
  if (synccookie) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.syncCookie)
}
inline ::AcFunDanmu::Im::Basic::SyncCookie* SessionFolderSyncResponse::release_synccookie() {
  
  ::AcFunDanmu::Im::Basic::SyncCookie* temp = _impl_.synccookie_;
  _impl_.synccookie_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::AcFunDanmu::Im::Basic::SyncCookie* SessionFolderSyncResponse::unsafe_arena_release_synccookie() {
  // @@protoc_insertion_point(field_release:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.syncCookie)
  
  ::AcFunDanmu::Im::Basic::SyncCookie* temp = _impl_.synccookie_;
  _impl_.synccookie_ = nullptr;
  return temp;
}
inline ::AcFunDanmu::Im::Basic::SyncCookie* SessionFolderSyncResponse::_internal_mutable_synccookie() {
  
  if (_impl_.synccookie_ == nullptr) {
    auto* p = CreateMaybeMessage<::AcFunDanmu::Im::Basic::SyncCookie>(GetArenaForAllocation());
    _impl_.synccookie_ = p;
  }
  return _impl_.synccookie_;
}
inline ::AcFunDanmu::Im::Basic::SyncCookie* SessionFolderSyncResponse::mutable_synccookie() {
  ::AcFunDanmu::Im::Basic::SyncCookie* _msg = _internal_mutable_synccookie();
  // @@protoc_insertion_point(field_mutable:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.syncCookie)
  return _msg;
}
inline void SessionFolderSyncResponse::set_allocated_synccookie(::AcFunDanmu::Im::Basic::SyncCookie* synccookie) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.synccookie_);
  }
  if (synccookie) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(synccookie));
    if (message_arena != submessage_arena) {
      synccookie = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, synccookie, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.synccookie_ = synccookie;
  // @@protoc_insertion_point(field_set_allocated:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.syncCookie)
}

// repeated .AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderBasic sessionFolderBasic = 2;
inline int SessionFolderSyncResponse::_internal_sessionfolderbasic_size() const {
  return _impl_.sessionfolderbasic_.size();
}
inline int SessionFolderSyncResponse::sessionfolderbasic_size() const {
  return _internal_sessionfolderbasic_size();
}
inline ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderBasic* SessionFolderSyncResponse::mutable_sessionfolderbasic(int index) {
  // @@protoc_insertion_point(field_mutable:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.sessionFolderBasic)
  return _impl_.sessionfolderbasic_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderBasic >*
SessionFolderSyncResponse::mutable_sessionfolderbasic() {
  // @@protoc_insertion_point(field_mutable_list:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.sessionFolderBasic)
  return &_impl_.sessionfolderbasic_;
}
inline const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderBasic& SessionFolderSyncResponse::_internal_sessionfolderbasic(int index) const {
  return _impl_.sessionfolderbasic_.Get(index);
}
inline const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderBasic& SessionFolderSyncResponse::sessionfolderbasic(int index) const {
  // @@protoc_insertion_point(field_get:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.sessionFolderBasic)
  return _internal_sessionfolderbasic(index);
}
inline ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderBasic* SessionFolderSyncResponse::_internal_add_sessionfolderbasic() {
  return _impl_.sessionfolderbasic_.Add();
}
inline ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderBasic* SessionFolderSyncResponse::add_sessionfolderbasic() {
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderBasic* _add = _internal_add_sessionfolderbasic();
  // @@protoc_insertion_point(field_add:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.sessionFolderBasic)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderBasic >&
SessionFolderSyncResponse::sessionfolderbasic() const {
  // @@protoc_insertion_point(field_list:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.sessionFolderBasic)
  return _impl_.sessionfolderbasic_;
}

// repeated .AcFunDanmu.Im.Cloud.SessionFolder.SessionReferenceUpdateItem added = 3;
inline int SessionFolderSyncResponse::_internal_added_size() const {
  return _impl_.added_.size();
}
inline int SessionFolderSyncResponse::added_size() const {
  return _internal_added_size();
}
inline ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem* SessionFolderSyncResponse::mutable_added(int index) {
  // @@protoc_insertion_point(field_mutable:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.added)
  return _impl_.added_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem >*
SessionFolderSyncResponse::mutable_added() {
  // @@protoc_insertion_point(field_mutable_list:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.added)
  return &_impl_.added_;
}
inline const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem& SessionFolderSyncResponse::_internal_added(int index) const {
  return _impl_.added_.Get(index);
}
inline const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem& SessionFolderSyncResponse::added(int index) const {
  // @@protoc_insertion_point(field_get:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.added)
  return _internal_added(index);
}
inline ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem* SessionFolderSyncResponse::_internal_add_added() {
  return _impl_.added_.Add();
}
inline ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem* SessionFolderSyncResponse::add_added() {
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem* _add = _internal_add_added();
  // @@protoc_insertion_point(field_add:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.added)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem >&
SessionFolderSyncResponse::added() const {
  // @@protoc_insertion_point(field_list:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.added)
  return _impl_.added_;
}

// repeated .AcFunDanmu.Im.Cloud.SessionFolder.SessionReferenceUpdateItem removed = 4;
inline int SessionFolderSyncResponse::_internal_removed_size() const {
  return _impl_.removed_.size();
}
inline int SessionFolderSyncResponse::removed_size() const {
  return _internal_removed_size();
}
inline ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem* SessionFolderSyncResponse::mutable_removed(int index) {
  // @@protoc_insertion_point(field_mutable:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.removed)
  return _impl_.removed_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem >*
SessionFolderSyncResponse::mutable_removed() {
  // @@protoc_insertion_point(field_mutable_list:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.removed)
  return &_impl_.removed_;
}
inline const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem& SessionFolderSyncResponse::_internal_removed(int index) const {
  return _impl_.removed_.Get(index);
}
inline const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem& SessionFolderSyncResponse::removed(int index) const {
  // @@protoc_insertion_point(field_get:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.removed)
  return _internal_removed(index);
}
inline ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem* SessionFolderSyncResponse::_internal_add_removed() {
  return _impl_.removed_.Add();
}
inline ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem* SessionFolderSyncResponse::add_removed() {
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem* _add = _internal_add_removed();
  // @@protoc_insertion_point(field_add:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.removed)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::Im::Cloud::SessionFolder::SessionReferenceUpdateItem >&
SessionFolderSyncResponse::removed() const {
  // @@protoc_insertion_point(field_list:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.removed)
  return _impl_.removed_;
}

// bool notFullFetch = 5;
inline void SessionFolderSyncResponse::clear_notfullfetch() {
  _impl_.notfullfetch_ = false;
}
inline bool SessionFolderSyncResponse::_internal_notfullfetch() const {
  return _impl_.notfullfetch_;
}
inline bool SessionFolderSyncResponse::notfullfetch() const {
  // @@protoc_insertion_point(field_get:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.notFullFetch)
  return _internal_notfullfetch();
}
inline void SessionFolderSyncResponse::_internal_set_notfullfetch(bool value) {
  
  _impl_.notfullfetch_ = value;
}
inline void SessionFolderSyncResponse::set_notfullfetch(bool value) {
  _internal_set_notfullfetch(value);
  // @@protoc_insertion_point(field_set:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.notFullFetch)
}

// bool clearLocalData = 6;
inline void SessionFolderSyncResponse::clear_clearlocaldata() {
  _impl_.clearlocaldata_ = false;
}
inline bool SessionFolderSyncResponse::_internal_clearlocaldata() const {
  return _impl_.clearlocaldata_;
}
inline bool SessionFolderSyncResponse::clearlocaldata() const {
  // @@protoc_insertion_point(field_get:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.clearLocalData)
  return _internal_clearlocaldata();
}
inline void SessionFolderSyncResponse::_internal_set_clearlocaldata(bool value) {
  
  _impl_.clearlocaldata_ = value;
}
inline void SessionFolderSyncResponse::set_clearlocaldata(bool value) {
  _internal_set_clearlocaldata(value);
  // @@protoc_insertion_point(field_set:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderSyncResponse.clearLocalData)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace SessionFolder
}  // namespace Cloud
}  // namespace Im
}  // namespace AcFunDanmu

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_SessionFolderSyncResponse_2eproto
