// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SessionFolderCreateResponse.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_SessionFolderCreateResponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_SessionFolderCreateResponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "SessionFolderInfo.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_SessionFolderCreateResponse_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_SessionFolderCreateResponse_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_SessionFolderCreateResponse_2eproto;
namespace AcFunDanmu {
namespace Im {
namespace Cloud {
namespace SessionFolder {
class SessionFolderCreateResponse;
struct SessionFolderCreateResponseDefaultTypeInternal;
extern SessionFolderCreateResponseDefaultTypeInternal _SessionFolderCreateResponse_default_instance_;
}  // namespace SessionFolder
}  // namespace Cloud
}  // namespace Im
}  // namespace AcFunDanmu
PROTOBUF_NAMESPACE_OPEN
template<> ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderCreateResponse* Arena::CreateMaybeMessage<::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderCreateResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace AcFunDanmu {
namespace Im {
namespace Cloud {
namespace SessionFolder {

// ===================================================================

class SessionFolderCreateResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderCreateResponse) */ {
 public:
  inline SessionFolderCreateResponse() : SessionFolderCreateResponse(nullptr) {}
  ~SessionFolderCreateResponse() override;
  explicit PROTOBUF_CONSTEXPR SessionFolderCreateResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SessionFolderCreateResponse(const SessionFolderCreateResponse& from);
  SessionFolderCreateResponse(SessionFolderCreateResponse&& from) noexcept
    : SessionFolderCreateResponse() {
    *this = ::std::move(from);
  }

  inline SessionFolderCreateResponse& operator=(const SessionFolderCreateResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SessionFolderCreateResponse& operator=(SessionFolderCreateResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SessionFolderCreateResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SessionFolderCreateResponse* internal_default_instance() {
    return reinterpret_cast<const SessionFolderCreateResponse*>(
               &_SessionFolderCreateResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SessionFolderCreateResponse& a, SessionFolderCreateResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SessionFolderCreateResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SessionFolderCreateResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SessionFolderCreateResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SessionFolderCreateResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SessionFolderCreateResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SessionFolderCreateResponse& from) {
    SessionFolderCreateResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SessionFolderCreateResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderCreateResponse";
  }
  protected:
  explicit SessionFolderCreateResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionFolderInfoFieldNumber = 1,
  };
  // .AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderInfo sessionFolderInfo = 1;
  bool has_sessionfolderinfo() const;
  private:
  bool _internal_has_sessionfolderinfo() const;
  public:
  void clear_sessionfolderinfo();
  const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo& sessionfolderinfo() const;
  PROTOBUF_NODISCARD ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* release_sessionfolderinfo();
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* mutable_sessionfolderinfo();
  void set_allocated_sessionfolderinfo(::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* sessionfolderinfo);
  private:
  const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo& _internal_sessionfolderinfo() const;
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* _internal_mutable_sessionfolderinfo();
  public:
  void unsafe_arena_set_allocated_sessionfolderinfo(
      ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* sessionfolderinfo);
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* unsafe_arena_release_sessionfolderinfo();

  // @@protoc_insertion_point(class_scope:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderCreateResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* sessionfolderinfo_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SessionFolderCreateResponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SessionFolderCreateResponse

// .AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderInfo sessionFolderInfo = 1;
inline bool SessionFolderCreateResponse::_internal_has_sessionfolderinfo() const {
  return this != internal_default_instance() && _impl_.sessionfolderinfo_ != nullptr;
}
inline bool SessionFolderCreateResponse::has_sessionfolderinfo() const {
  return _internal_has_sessionfolderinfo();
}
inline const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo& SessionFolderCreateResponse::_internal_sessionfolderinfo() const {
  const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* p = _impl_.sessionfolderinfo_;
  return p != nullptr ? *p : reinterpret_cast<const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo&>(
      ::AcFunDanmu::Im::Cloud::SessionFolder::_SessionFolderInfo_default_instance_);
}
inline const ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo& SessionFolderCreateResponse::sessionfolderinfo() const {
  // @@protoc_insertion_point(field_get:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderCreateResponse.sessionFolderInfo)
  return _internal_sessionfolderinfo();
}
inline void SessionFolderCreateResponse::unsafe_arena_set_allocated_sessionfolderinfo(
    ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* sessionfolderinfo) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.sessionfolderinfo_);
  }
  _impl_.sessionfolderinfo_ = sessionfolderinfo;
  if (sessionfolderinfo) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderCreateResponse.sessionFolderInfo)
}
inline ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* SessionFolderCreateResponse::release_sessionfolderinfo() {
  
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* temp = _impl_.sessionfolderinfo_;
  _impl_.sessionfolderinfo_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* SessionFolderCreateResponse::unsafe_arena_release_sessionfolderinfo() {
  // @@protoc_insertion_point(field_release:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderCreateResponse.sessionFolderInfo)
  
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* temp = _impl_.sessionfolderinfo_;
  _impl_.sessionfolderinfo_ = nullptr;
  return temp;
}
inline ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* SessionFolderCreateResponse::_internal_mutable_sessionfolderinfo() {
  
  if (_impl_.sessionfolderinfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo>(GetArenaForAllocation());
    _impl_.sessionfolderinfo_ = p;
  }
  return _impl_.sessionfolderinfo_;
}
inline ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* SessionFolderCreateResponse::mutable_sessionfolderinfo() {
  ::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* _msg = _internal_mutable_sessionfolderinfo();
  // @@protoc_insertion_point(field_mutable:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderCreateResponse.sessionFolderInfo)
  return _msg;
}
inline void SessionFolderCreateResponse::set_allocated_sessionfolderinfo(::AcFunDanmu::Im::Cloud::SessionFolder::SessionFolderInfo* sessionfolderinfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.sessionfolderinfo_);
  }
  if (sessionfolderinfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(sessionfolderinfo));
    if (message_arena != submessage_arena) {
      sessionfolderinfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sessionfolderinfo, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.sessionfolderinfo_ = sessionfolderinfo;
  // @@protoc_insertion_point(field_set_allocated:AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderCreateResponse.sessionFolderInfo)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace SessionFolder
}  // namespace Cloud
}  // namespace Im
}  // namespace AcFunDanmu

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_SessionFolderCreateResponse_2eproto
