// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VoiceCallMessageContent.proto

#include "VoiceCallMessageContent.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace AcFunDanmu {
namespace Im {
namespace Cloud {
namespace Message {
PROTOBUF_CONSTEXPR VoiceCallMessageContent::VoiceCallMessageContent(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.participant_)*/{}
  , /*decltype(_impl_.roomid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.title_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.fromuser_)*/nullptr
  , /*decltype(_impl_.host_)*/nullptr
  , /*decltype(_impl_.calltype_)*/0
  , /*decltype(_impl_.status_)*/0
  , /*decltype(_impl_.starttimems_)*/int64_t{0}
  , /*decltype(_impl_.endtimems_)*/int64_t{0}
  , /*decltype(_impl_.chatmode_)*/0
  , /*decltype(_impl_.maxcount_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct VoiceCallMessageContentDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VoiceCallMessageContentDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VoiceCallMessageContentDefaultTypeInternal() {}
  union {
    VoiceCallMessageContent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VoiceCallMessageContentDefaultTypeInternal _VoiceCallMessageContent_default_instance_;
}  // namespace Message
}  // namespace Cloud
}  // namespace Im
}  // namespace AcFunDanmu
static ::_pb::Metadata file_level_metadata_VoiceCallMessageContent_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_VoiceCallMessageContent_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_VoiceCallMessageContent_2eproto = nullptr;

const uint32_t TableStruct_VoiceCallMessageContent_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::AcFunDanmu::Im::Cloud::Message::VoiceCallMessageContent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::AcFunDanmu::Im::Cloud::Message::VoiceCallMessageContent, _impl_.roomid_),
  PROTOBUF_FIELD_OFFSET(::AcFunDanmu::Im::Cloud::Message::VoiceCallMessageContent, _impl_.calltype_),
  PROTOBUF_FIELD_OFFSET(::AcFunDanmu::Im::Cloud::Message::VoiceCallMessageContent, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::AcFunDanmu::Im::Cloud::Message::VoiceCallMessageContent, _impl_.starttimems_),
  PROTOBUF_FIELD_OFFSET(::AcFunDanmu::Im::Cloud::Message::VoiceCallMessageContent, _impl_.endtimems_),
  PROTOBUF_FIELD_OFFSET(::AcFunDanmu::Im::Cloud::Message::VoiceCallMessageContent, _impl_.fromuser_),
  PROTOBUF_FIELD_OFFSET(::AcFunDanmu::Im::Cloud::Message::VoiceCallMessageContent, _impl_.chatmode_),
  PROTOBUF_FIELD_OFFSET(::AcFunDanmu::Im::Cloud::Message::VoiceCallMessageContent, _impl_.title_),
  PROTOBUF_FIELD_OFFSET(::AcFunDanmu::Im::Cloud::Message::VoiceCallMessageContent, _impl_.host_),
  PROTOBUF_FIELD_OFFSET(::AcFunDanmu::Im::Cloud::Message::VoiceCallMessageContent, _impl_.participant_),
  PROTOBUF_FIELD_OFFSET(::AcFunDanmu::Im::Cloud::Message::VoiceCallMessageContent, _impl_.maxcount_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::AcFunDanmu::Im::Cloud::Message::VoiceCallMessageContent)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::AcFunDanmu::Im::Cloud::Message::_VoiceCallMessageContent_default_instance_._instance,
};

const char descriptor_table_protodef_VoiceCallMessageContent_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035VoiceCallMessageContent.proto\022\033AcFunDa"
  "nmu.Im.Cloud.Message\032\020CallStatus.proto\032\016"
  "CallType.proto\032\016ChatMode.proto\032\nUser.pro"
  "to\"\254\003\n\027VoiceCallMessageContent\022\016\n\006roomId"
  "\030\001 \001(\t\022:\n\010callType\030\002 \001(\0162(.AcFunDanmu.Im"
  ".Cloud.Voice.Call.CallType\022:\n\006status\030\003 \001"
  "(\0162*.AcFunDanmu.Im.Cloud.Voice.Call.Call"
  "Status\022\023\n\013startTimeMs\030\004 \001(\003\022\021\n\tendTimeMs"
  "\030\005 \001(\003\022+\n\010fromUser\030\006 \001(\0132\031.AcFunDanmu.Im"
  ".Basic.User\022:\n\010chatMode\030\007 \001(\0162(.AcFunDan"
  "mu.Im.Cloud.Voice.Call.ChatMode\022\r\n\005title"
  "\030\025 \001(\t\022\'\n\004host\030\026 \001(\0132\031.AcFunDanmu.Im.Bas"
  "ic.User\022.\n\013participant\030\027 \003(\0132\031.AcFunDanm"
  "u.Im.Basic.User\022\020\n\010maxCount\030\030 \001(\005b\006proto"
  "3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_VoiceCallMessageContent_2eproto_deps[4] = {
  &::descriptor_table_CallStatus_2eproto,
  &::descriptor_table_CallType_2eproto,
  &::descriptor_table_ChatMode_2eproto,
  &::descriptor_table_User_2eproto,
};
static ::_pbi::once_flag descriptor_table_VoiceCallMessageContent_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_VoiceCallMessageContent_2eproto = {
    false, false, 561, descriptor_table_protodef_VoiceCallMessageContent_2eproto,
    "VoiceCallMessageContent.proto",
    &descriptor_table_VoiceCallMessageContent_2eproto_once, descriptor_table_VoiceCallMessageContent_2eproto_deps, 4, 1,
    schemas, file_default_instances, TableStruct_VoiceCallMessageContent_2eproto::offsets,
    file_level_metadata_VoiceCallMessageContent_2eproto, file_level_enum_descriptors_VoiceCallMessageContent_2eproto,
    file_level_service_descriptors_VoiceCallMessageContent_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_VoiceCallMessageContent_2eproto_getter() {
  return &descriptor_table_VoiceCallMessageContent_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_VoiceCallMessageContent_2eproto(&descriptor_table_VoiceCallMessageContent_2eproto);
namespace AcFunDanmu {
namespace Im {
namespace Cloud {
namespace Message {

// ===================================================================

class VoiceCallMessageContent::_Internal {
 public:
  static const ::AcFunDanmu::Im::Basic::User& fromuser(const VoiceCallMessageContent* msg);
  static const ::AcFunDanmu::Im::Basic::User& host(const VoiceCallMessageContent* msg);
};

const ::AcFunDanmu::Im::Basic::User&
VoiceCallMessageContent::_Internal::fromuser(const VoiceCallMessageContent* msg) {
  return *msg->_impl_.fromuser_;
}
const ::AcFunDanmu::Im::Basic::User&
VoiceCallMessageContent::_Internal::host(const VoiceCallMessageContent* msg) {
  return *msg->_impl_.host_;
}
void VoiceCallMessageContent::clear_fromuser() {
  if (GetArenaForAllocation() == nullptr && _impl_.fromuser_ != nullptr) {
    delete _impl_.fromuser_;
  }
  _impl_.fromuser_ = nullptr;
}
void VoiceCallMessageContent::clear_host() {
  if (GetArenaForAllocation() == nullptr && _impl_.host_ != nullptr) {
    delete _impl_.host_;
  }
  _impl_.host_ = nullptr;
}
void VoiceCallMessageContent::clear_participant() {
  _impl_.participant_.Clear();
}
VoiceCallMessageContent::VoiceCallMessageContent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:AcFunDanmu.Im.Cloud.Message.VoiceCallMessageContent)
}
VoiceCallMessageContent::VoiceCallMessageContent(const VoiceCallMessageContent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  VoiceCallMessageContent* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.participant_){from._impl_.participant_}
    , decltype(_impl_.roomid_){}
    , decltype(_impl_.title_){}
    , decltype(_impl_.fromuser_){nullptr}
    , decltype(_impl_.host_){nullptr}
    , decltype(_impl_.calltype_){}
    , decltype(_impl_.status_){}
    , decltype(_impl_.starttimems_){}
    , decltype(_impl_.endtimems_){}
    , decltype(_impl_.chatmode_){}
    , decltype(_impl_.maxcount_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.roomid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.roomid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_roomid().empty()) {
    _this->_impl_.roomid_.Set(from._internal_roomid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.title_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.title_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_title().empty()) {
    _this->_impl_.title_.Set(from._internal_title(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_fromuser()) {
    _this->_impl_.fromuser_ = new ::AcFunDanmu::Im::Basic::User(*from._impl_.fromuser_);
  }
  if (from._internal_has_host()) {
    _this->_impl_.host_ = new ::AcFunDanmu::Im::Basic::User(*from._impl_.host_);
  }
  ::memcpy(&_impl_.calltype_, &from._impl_.calltype_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.maxcount_) -
    reinterpret_cast<char*>(&_impl_.calltype_)) + sizeof(_impl_.maxcount_));
  // @@protoc_insertion_point(copy_constructor:AcFunDanmu.Im.Cloud.Message.VoiceCallMessageContent)
}

inline void VoiceCallMessageContent::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.participant_){arena}
    , decltype(_impl_.roomid_){}
    , decltype(_impl_.title_){}
    , decltype(_impl_.fromuser_){nullptr}
    , decltype(_impl_.host_){nullptr}
    , decltype(_impl_.calltype_){0}
    , decltype(_impl_.status_){0}
    , decltype(_impl_.starttimems_){int64_t{0}}
    , decltype(_impl_.endtimems_){int64_t{0}}
    , decltype(_impl_.chatmode_){0}
    , decltype(_impl_.maxcount_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.roomid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.roomid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.title_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.title_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

VoiceCallMessageContent::~VoiceCallMessageContent() {
  // @@protoc_insertion_point(destructor:AcFunDanmu.Im.Cloud.Message.VoiceCallMessageContent)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void VoiceCallMessageContent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.participant_.~RepeatedPtrField();
  _impl_.roomid_.Destroy();
  _impl_.title_.Destroy();
  if (this != internal_default_instance()) delete _impl_.fromuser_;
  if (this != internal_default_instance()) delete _impl_.host_;
}

void VoiceCallMessageContent::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void VoiceCallMessageContent::Clear() {
// @@protoc_insertion_point(message_clear_start:AcFunDanmu.Im.Cloud.Message.VoiceCallMessageContent)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.participant_.Clear();
  _impl_.roomid_.ClearToEmpty();
  _impl_.title_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.fromuser_ != nullptr) {
    delete _impl_.fromuser_;
  }
  _impl_.fromuser_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.host_ != nullptr) {
    delete _impl_.host_;
  }
  _impl_.host_ = nullptr;
  ::memset(&_impl_.calltype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.maxcount_) -
      reinterpret_cast<char*>(&_impl_.calltype_)) + sizeof(_impl_.maxcount_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VoiceCallMessageContent::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string roomId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_roomid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "AcFunDanmu.Im.Cloud.Message.VoiceCallMessageContent.roomId"));
        } else
          goto handle_unusual;
        continue;
      // .AcFunDanmu.Im.Cloud.Voice.Call.CallType callType = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_calltype(static_cast<::AcFunDanmu::Im::Cloud::Voice::Call::CallType>(val));
        } else
          goto handle_unusual;
        continue;
      // .AcFunDanmu.Im.Cloud.Voice.Call.CallStatus status = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::AcFunDanmu::Im::Cloud::Voice::Call::CallStatus>(val));
        } else
          goto handle_unusual;
        continue;
      // int64 startTimeMs = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.starttimems_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 endTimeMs = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.endtimems_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .AcFunDanmu.Im.Basic.User fromUser = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_fromuser(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .AcFunDanmu.Im.Cloud.Voice.Call.ChatMode chatMode = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_chatmode(static_cast<::AcFunDanmu::Im::Cloud::Voice::Call::ChatMode>(val));
        } else
          goto handle_unusual;
        continue;
      // string title = 21;
      case 21:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 170)) {
          auto str = _internal_mutable_title();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "AcFunDanmu.Im.Cloud.Message.VoiceCallMessageContent.title"));
        } else
          goto handle_unusual;
        continue;
      // .AcFunDanmu.Im.Basic.User host = 22;
      case 22:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 178)) {
          ptr = ctx->ParseMessage(_internal_mutable_host(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .AcFunDanmu.Im.Basic.User participant = 23;
      case 23:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 186)) {
          ptr -= 2;
          do {
            ptr += 2;
            ptr = ctx->ParseMessage(_internal_add_participant(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<186>(ptr));
        } else
          goto handle_unusual;
        continue;
      // int32 maxCount = 24;
      case 24:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 192)) {
          _impl_.maxcount_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* VoiceCallMessageContent::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:AcFunDanmu.Im.Cloud.Message.VoiceCallMessageContent)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string roomId = 1;
  if (!this->_internal_roomid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_roomid().data(), static_cast<int>(this->_internal_roomid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "AcFunDanmu.Im.Cloud.Message.VoiceCallMessageContent.roomId");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_roomid(), target);
  }

  // .AcFunDanmu.Im.Cloud.Voice.Call.CallType callType = 2;
  if (this->_internal_calltype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_calltype(), target);
  }

  // .AcFunDanmu.Im.Cloud.Voice.Call.CallStatus status = 3;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_status(), target);
  }

  // int64 startTimeMs = 4;
  if (this->_internal_starttimems() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_starttimems(), target);
  }

  // int64 endTimeMs = 5;
  if (this->_internal_endtimems() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(5, this->_internal_endtimems(), target);
  }

  // .AcFunDanmu.Im.Basic.User fromUser = 6;
  if (this->_internal_has_fromuser()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::fromuser(this),
        _Internal::fromuser(this).GetCachedSize(), target, stream);
  }

  // .AcFunDanmu.Im.Cloud.Voice.Call.ChatMode chatMode = 7;
  if (this->_internal_chatmode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      7, this->_internal_chatmode(), target);
  }

  // string title = 21;
  if (!this->_internal_title().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_title().data(), static_cast<int>(this->_internal_title().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "AcFunDanmu.Im.Cloud.Message.VoiceCallMessageContent.title");
    target = stream->WriteStringMaybeAliased(
        21, this->_internal_title(), target);
  }

  // .AcFunDanmu.Im.Basic.User host = 22;
  if (this->_internal_has_host()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(22, _Internal::host(this),
        _Internal::host(this).GetCachedSize(), target, stream);
  }

  // repeated .AcFunDanmu.Im.Basic.User participant = 23;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_participant_size()); i < n; i++) {
    const auto& repfield = this->_internal_participant(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(23, repfield, repfield.GetCachedSize(), target, stream);
  }

  // int32 maxCount = 24;
  if (this->_internal_maxcount() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(24, this->_internal_maxcount(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AcFunDanmu.Im.Cloud.Message.VoiceCallMessageContent)
  return target;
}

size_t VoiceCallMessageContent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AcFunDanmu.Im.Cloud.Message.VoiceCallMessageContent)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .AcFunDanmu.Im.Basic.User participant = 23;
  total_size += 2UL * this->_internal_participant_size();
  for (const auto& msg : this->_impl_.participant_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string roomId = 1;
  if (!this->_internal_roomid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_roomid());
  }

  // string title = 21;
  if (!this->_internal_title().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_title());
  }

  // .AcFunDanmu.Im.Basic.User fromUser = 6;
  if (this->_internal_has_fromuser()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.fromuser_);
  }

  // .AcFunDanmu.Im.Basic.User host = 22;
  if (this->_internal_has_host()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.host_);
  }

  // .AcFunDanmu.Im.Cloud.Voice.Call.CallType callType = 2;
  if (this->_internal_calltype() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_calltype());
  }

  // .AcFunDanmu.Im.Cloud.Voice.Call.CallStatus status = 3;
  if (this->_internal_status() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }

  // int64 startTimeMs = 4;
  if (this->_internal_starttimems() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_starttimems());
  }

  // int64 endTimeMs = 5;
  if (this->_internal_endtimems() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_endtimems());
  }

  // .AcFunDanmu.Im.Cloud.Voice.Call.ChatMode chatMode = 7;
  if (this->_internal_chatmode() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_chatmode());
  }

  // int32 maxCount = 24;
  if (this->_internal_maxcount() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int32Size(
        this->_internal_maxcount());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData VoiceCallMessageContent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    VoiceCallMessageContent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*VoiceCallMessageContent::GetClassData() const { return &_class_data_; }


void VoiceCallMessageContent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<VoiceCallMessageContent*>(&to_msg);
  auto& from = static_cast<const VoiceCallMessageContent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AcFunDanmu.Im.Cloud.Message.VoiceCallMessageContent)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.participant_.MergeFrom(from._impl_.participant_);
  if (!from._internal_roomid().empty()) {
    _this->_internal_set_roomid(from._internal_roomid());
  }
  if (!from._internal_title().empty()) {
    _this->_internal_set_title(from._internal_title());
  }
  if (from._internal_has_fromuser()) {
    _this->_internal_mutable_fromuser()->::AcFunDanmu::Im::Basic::User::MergeFrom(
        from._internal_fromuser());
  }
  if (from._internal_has_host()) {
    _this->_internal_mutable_host()->::AcFunDanmu::Im::Basic::User::MergeFrom(
        from._internal_host());
  }
  if (from._internal_calltype() != 0) {
    _this->_internal_set_calltype(from._internal_calltype());
  }
  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  if (from._internal_starttimems() != 0) {
    _this->_internal_set_starttimems(from._internal_starttimems());
  }
  if (from._internal_endtimems() != 0) {
    _this->_internal_set_endtimems(from._internal_endtimems());
  }
  if (from._internal_chatmode() != 0) {
    _this->_internal_set_chatmode(from._internal_chatmode());
  }
  if (from._internal_maxcount() != 0) {
    _this->_internal_set_maxcount(from._internal_maxcount());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void VoiceCallMessageContent::CopyFrom(const VoiceCallMessageContent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AcFunDanmu.Im.Cloud.Message.VoiceCallMessageContent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VoiceCallMessageContent::IsInitialized() const {
  return true;
}

void VoiceCallMessageContent::InternalSwap(VoiceCallMessageContent* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.participant_.InternalSwap(&other->_impl_.participant_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.roomid_, lhs_arena,
      &other->_impl_.roomid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.title_, lhs_arena,
      &other->_impl_.title_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VoiceCallMessageContent, _impl_.maxcount_)
      + sizeof(VoiceCallMessageContent::_impl_.maxcount_)
      - PROTOBUF_FIELD_OFFSET(VoiceCallMessageContent, _impl_.fromuser_)>(
          reinterpret_cast<char*>(&_impl_.fromuser_),
          reinterpret_cast<char*>(&other->_impl_.fromuser_));
}

::PROTOBUF_NAMESPACE_ID::Metadata VoiceCallMessageContent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_VoiceCallMessageContent_2eproto_getter, &descriptor_table_VoiceCallMessageContent_2eproto_once,
      file_level_metadata_VoiceCallMessageContent_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Message
}  // namespace Cloud
}  // namespace Im
}  // namespace AcFunDanmu
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::AcFunDanmu::Im::Cloud::Message::VoiceCallMessageContent*
Arena::CreateMaybeMessage< ::AcFunDanmu::Im::Cloud::Message::VoiceCallMessageContent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::AcFunDanmu::Im::Cloud::Message::VoiceCallMessageContent >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
