// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ZtLiveActionSignalItem.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ZtLiveActionSignalItem_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ZtLiveActionSignalItem_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ZtLiveActionSignalItem_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ZtLiveActionSignalItem_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ZtLiveActionSignalItem_2eproto;
namespace AcFunDanmu {
class ZtLiveActionSignalItem;
class ZtLiveActionSignalItemDefaultTypeInternal;
extern ZtLiveActionSignalItemDefaultTypeInternal _ZtLiveActionSignalItem_default_instance_;
}  // namespace AcFunDanmu
PROTOBUF_NAMESPACE_OPEN
template<> ::AcFunDanmu::ZtLiveActionSignalItem* Arena::CreateMaybeMessage<::AcFunDanmu::ZtLiveActionSignalItem>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace AcFunDanmu {

// ===================================================================

class ZtLiveActionSignalItem PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:AcFunDanmu.ZtLiveActionSignalItem) */ {
 public:
  inline ZtLiveActionSignalItem() : ZtLiveActionSignalItem(nullptr) {}
  virtual ~ZtLiveActionSignalItem();

  ZtLiveActionSignalItem(const ZtLiveActionSignalItem& from);
  ZtLiveActionSignalItem(ZtLiveActionSignalItem&& from) noexcept
    : ZtLiveActionSignalItem() {
    *this = ::std::move(from);
  }

  inline ZtLiveActionSignalItem& operator=(const ZtLiveActionSignalItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline ZtLiveActionSignalItem& operator=(ZtLiveActionSignalItem&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ZtLiveActionSignalItem& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ZtLiveActionSignalItem* internal_default_instance() {
    return reinterpret_cast<const ZtLiveActionSignalItem*>(
               &_ZtLiveActionSignalItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ZtLiveActionSignalItem& a, ZtLiveActionSignalItem& b) {
    a.Swap(&b);
  }
  inline void Swap(ZtLiveActionSignalItem* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ZtLiveActionSignalItem* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ZtLiveActionSignalItem* New() const final {
    return CreateMaybeMessage<ZtLiveActionSignalItem>(nullptr);
  }

  ZtLiveActionSignalItem* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ZtLiveActionSignalItem>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ZtLiveActionSignalItem& from);
  void MergeFrom(const ZtLiveActionSignalItem& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ZtLiveActionSignalItem* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "AcFunDanmu.ZtLiveActionSignalItem";
  }
  protected:
  explicit ZtLiveActionSignalItem(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ZtLiveActionSignalItem_2eproto);
    return ::descriptor_table_ZtLiveActionSignalItem_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPayloadFieldNumber = 2,
    kSignalTypeFieldNumber = 1,
  };
  // repeated bytes payload = 2;
  int payload_size() const;
  private:
  int _internal_payload_size() const;
  public:
  void clear_payload();
  const std::string& payload(int index) const;
  std::string* mutable_payload(int index);
  void set_payload(int index, const std::string& value);
  void set_payload(int index, std::string&& value);
  void set_payload(int index, const char* value);
  void set_payload(int index, const void* value, size_t size);
  std::string* add_payload();
  void add_payload(const std::string& value);
  void add_payload(std::string&& value);
  void add_payload(const char* value);
  void add_payload(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& payload() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_payload();
  private:
  const std::string& _internal_payload(int index) const;
  std::string* _internal_add_payload();
  public:

  // string signalType = 1;
  void clear_signaltype();
  const std::string& signaltype() const;
  void set_signaltype(const std::string& value);
  void set_signaltype(std::string&& value);
  void set_signaltype(const char* value);
  void set_signaltype(const char* value, size_t size);
  std::string* mutable_signaltype();
  std::string* release_signaltype();
  void set_allocated_signaltype(std::string* signaltype);
  private:
  const std::string& _internal_signaltype() const;
  void _internal_set_signaltype(const std::string& value);
  std::string* _internal_mutable_signaltype();
  public:

  // @@protoc_insertion_point(class_scope:AcFunDanmu.ZtLiveActionSignalItem)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> payload_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr signaltype_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ZtLiveActionSignalItem_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ZtLiveActionSignalItem

// string signalType = 1;
inline void ZtLiveActionSignalItem::clear_signaltype() {
  signaltype_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ZtLiveActionSignalItem::signaltype() const {
  // @@protoc_insertion_point(field_get:AcFunDanmu.ZtLiveActionSignalItem.signalType)
  return _internal_signaltype();
}
inline void ZtLiveActionSignalItem::set_signaltype(const std::string& value) {
  _internal_set_signaltype(value);
  // @@protoc_insertion_point(field_set:AcFunDanmu.ZtLiveActionSignalItem.signalType)
}
inline std::string* ZtLiveActionSignalItem::mutable_signaltype() {
  // @@protoc_insertion_point(field_mutable:AcFunDanmu.ZtLiveActionSignalItem.signalType)
  return _internal_mutable_signaltype();
}
inline const std::string& ZtLiveActionSignalItem::_internal_signaltype() const {
  return signaltype_.Get();
}
inline void ZtLiveActionSignalItem::_internal_set_signaltype(const std::string& value) {
  
  signaltype_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ZtLiveActionSignalItem::set_signaltype(std::string&& value) {
  
  signaltype_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:AcFunDanmu.ZtLiveActionSignalItem.signalType)
}
inline void ZtLiveActionSignalItem::set_signaltype(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  signaltype_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:AcFunDanmu.ZtLiveActionSignalItem.signalType)
}
inline void ZtLiveActionSignalItem::set_signaltype(const char* value,
    size_t size) {
  
  signaltype_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:AcFunDanmu.ZtLiveActionSignalItem.signalType)
}
inline std::string* ZtLiveActionSignalItem::_internal_mutable_signaltype() {
  
  return signaltype_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ZtLiveActionSignalItem::release_signaltype() {
  // @@protoc_insertion_point(field_release:AcFunDanmu.ZtLiveActionSignalItem.signalType)
  return signaltype_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ZtLiveActionSignalItem::set_allocated_signaltype(std::string* signaltype) {
  if (signaltype != nullptr) {
    
  } else {
    
  }
  signaltype_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), signaltype,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:AcFunDanmu.ZtLiveActionSignalItem.signalType)
}

// repeated bytes payload = 2;
inline int ZtLiveActionSignalItem::_internal_payload_size() const {
  return payload_.size();
}
inline int ZtLiveActionSignalItem::payload_size() const {
  return _internal_payload_size();
}
inline void ZtLiveActionSignalItem::clear_payload() {
  payload_.Clear();
}
inline std::string* ZtLiveActionSignalItem::add_payload() {
  // @@protoc_insertion_point(field_add_mutable:AcFunDanmu.ZtLiveActionSignalItem.payload)
  return _internal_add_payload();
}
inline const std::string& ZtLiveActionSignalItem::_internal_payload(int index) const {
  return payload_.Get(index);
}
inline const std::string& ZtLiveActionSignalItem::payload(int index) const {
  // @@protoc_insertion_point(field_get:AcFunDanmu.ZtLiveActionSignalItem.payload)
  return _internal_payload(index);
}
inline std::string* ZtLiveActionSignalItem::mutable_payload(int index) {
  // @@protoc_insertion_point(field_mutable:AcFunDanmu.ZtLiveActionSignalItem.payload)
  return payload_.Mutable(index);
}
inline void ZtLiveActionSignalItem::set_payload(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:AcFunDanmu.ZtLiveActionSignalItem.payload)
  payload_.Mutable(index)->assign(value);
}
inline void ZtLiveActionSignalItem::set_payload(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:AcFunDanmu.ZtLiveActionSignalItem.payload)
  payload_.Mutable(index)->assign(std::move(value));
}
inline void ZtLiveActionSignalItem::set_payload(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  payload_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:AcFunDanmu.ZtLiveActionSignalItem.payload)
}
inline void ZtLiveActionSignalItem::set_payload(int index, const void* value, size_t size) {
  payload_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:AcFunDanmu.ZtLiveActionSignalItem.payload)
}
inline std::string* ZtLiveActionSignalItem::_internal_add_payload() {
  return payload_.Add();
}
inline void ZtLiveActionSignalItem::add_payload(const std::string& value) {
  payload_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:AcFunDanmu.ZtLiveActionSignalItem.payload)
}
inline void ZtLiveActionSignalItem::add_payload(std::string&& value) {
  payload_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:AcFunDanmu.ZtLiveActionSignalItem.payload)
}
inline void ZtLiveActionSignalItem::add_payload(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  payload_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:AcFunDanmu.ZtLiveActionSignalItem.payload)
}
inline void ZtLiveActionSignalItem::add_payload(const void* value, size_t size) {
  payload_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:AcFunDanmu.ZtLiveActionSignalItem.payload)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ZtLiveActionSignalItem::payload() const {
  // @@protoc_insertion_point(field_list:AcFunDanmu.ZtLiveActionSignalItem.payload)
  return payload_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ZtLiveActionSignalItem::mutable_payload() {
  // @@protoc_insertion_point(field_mutable_list:AcFunDanmu.ZtLiveActionSignalItem.payload)
  return &payload_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace AcFunDanmu

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ZtLiveActionSignalItem_2eproto
