// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ZtLiveScStateSignal.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ZtLiveScStateSignal_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ZtLiveScStateSignal_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ZtLiveStateSignalItem.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ZtLiveScStateSignal_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ZtLiveScStateSignal_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ZtLiveScStateSignal_2eproto;
namespace AcFunDanmu {
class ZtLiveScStateSignal;
struct ZtLiveScStateSignalDefaultTypeInternal;
extern ZtLiveScStateSignalDefaultTypeInternal _ZtLiveScStateSignal_default_instance_;
}  // namespace AcFunDanmu
PROTOBUF_NAMESPACE_OPEN
template<> ::AcFunDanmu::ZtLiveScStateSignal* Arena::CreateMaybeMessage<::AcFunDanmu::ZtLiveScStateSignal>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace AcFunDanmu {

// ===================================================================

class ZtLiveScStateSignal final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:AcFunDanmu.ZtLiveScStateSignal) */ {
 public:
  inline ZtLiveScStateSignal() : ZtLiveScStateSignal(nullptr) {}
  ~ZtLiveScStateSignal() override;
  explicit PROTOBUF_CONSTEXPR ZtLiveScStateSignal(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ZtLiveScStateSignal(const ZtLiveScStateSignal& from);
  ZtLiveScStateSignal(ZtLiveScStateSignal&& from) noexcept
    : ZtLiveScStateSignal() {
    *this = ::std::move(from);
  }

  inline ZtLiveScStateSignal& operator=(const ZtLiveScStateSignal& from) {
    CopyFrom(from);
    return *this;
  }
  inline ZtLiveScStateSignal& operator=(ZtLiveScStateSignal&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ZtLiveScStateSignal& default_instance() {
    return *internal_default_instance();
  }
  static inline const ZtLiveScStateSignal* internal_default_instance() {
    return reinterpret_cast<const ZtLiveScStateSignal*>(
               &_ZtLiveScStateSignal_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ZtLiveScStateSignal& a, ZtLiveScStateSignal& b) {
    a.Swap(&b);
  }
  inline void Swap(ZtLiveScStateSignal* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ZtLiveScStateSignal* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ZtLiveScStateSignal* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ZtLiveScStateSignal>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ZtLiveScStateSignal& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ZtLiveScStateSignal& from) {
    ZtLiveScStateSignal::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ZtLiveScStateSignal* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "AcFunDanmu.ZtLiveScStateSignal";
  }
  protected:
  explicit ZtLiveScStateSignal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemFieldNumber = 1,
  };
  // repeated .AcFunDanmu.ZtLiveStateSignalItem item = 1;
  int item_size() const;
  private:
  int _internal_item_size() const;
  public:
  void clear_item();
  ::AcFunDanmu::ZtLiveStateSignalItem* mutable_item(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::ZtLiveStateSignalItem >*
      mutable_item();
  private:
  const ::AcFunDanmu::ZtLiveStateSignalItem& _internal_item(int index) const;
  ::AcFunDanmu::ZtLiveStateSignalItem* _internal_add_item();
  public:
  const ::AcFunDanmu::ZtLiveStateSignalItem& item(int index) const;
  ::AcFunDanmu::ZtLiveStateSignalItem* add_item();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::ZtLiveStateSignalItem >&
      item() const;

  // @@protoc_insertion_point(class_scope:AcFunDanmu.ZtLiveScStateSignal)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::ZtLiveStateSignalItem > item_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ZtLiveScStateSignal_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ZtLiveScStateSignal

// repeated .AcFunDanmu.ZtLiveStateSignalItem item = 1;
inline int ZtLiveScStateSignal::_internal_item_size() const {
  return _impl_.item_.size();
}
inline int ZtLiveScStateSignal::item_size() const {
  return _internal_item_size();
}
inline ::AcFunDanmu::ZtLiveStateSignalItem* ZtLiveScStateSignal::mutable_item(int index) {
  // @@protoc_insertion_point(field_mutable:AcFunDanmu.ZtLiveScStateSignal.item)
  return _impl_.item_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::ZtLiveStateSignalItem >*
ZtLiveScStateSignal::mutable_item() {
  // @@protoc_insertion_point(field_mutable_list:AcFunDanmu.ZtLiveScStateSignal.item)
  return &_impl_.item_;
}
inline const ::AcFunDanmu::ZtLiveStateSignalItem& ZtLiveScStateSignal::_internal_item(int index) const {
  return _impl_.item_.Get(index);
}
inline const ::AcFunDanmu::ZtLiveStateSignalItem& ZtLiveScStateSignal::item(int index) const {
  // @@protoc_insertion_point(field_get:AcFunDanmu.ZtLiveScStateSignal.item)
  return _internal_item(index);
}
inline ::AcFunDanmu::ZtLiveStateSignalItem* ZtLiveScStateSignal::_internal_add_item() {
  return _impl_.item_.Add();
}
inline ::AcFunDanmu::ZtLiveStateSignalItem* ZtLiveScStateSignal::add_item() {
  ::AcFunDanmu::ZtLiveStateSignalItem* _add = _internal_add_item();
  // @@protoc_insertion_point(field_add:AcFunDanmu.ZtLiveScStateSignal.item)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::AcFunDanmu::ZtLiveStateSignalItem >&
ZtLiveScStateSignal::item() const {
  // @@protoc_insertion_point(field_list:AcFunDanmu.ZtLiveScStateSignal.item)
  return _impl_.item_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace AcFunDanmu

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ZtLiveScStateSignal_2eproto
